apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ej0i1isvx-python 
  janus-idp.io/tekton: ej0i1isvx-python
  backstage.io/kubernetes-id: ej0i1isvx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ej0i1isvx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml