apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ej0i1isvx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ej0i1isvx-python 
  name: ej0i1isvx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ej0i1isvx-python 
